name: CICD Preview
on:
  pull_request:
    paths:
    - 'cicd/**'

jobs:
  aws:
    runs-on: arm64-runner
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: unfor19/install-aws-cli-action@v1.0.3
      with:
        version: 2
        arch: arm64
    - run: npm install && make reviewable
      working-directory: cicd
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: aws
        work-dir: cicd
        comment-on-pr: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
