name: CICD
on:
  pull_request:
    paths:
    - 'cicd/**'

jobs:
  preview:
    runs-on: arm64-runner
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/preview
      with:
        dir: cicd
        stack: aws
