name: EKS
on:
  pull_request:
    paths:
    - 'eks/**'

jobs:
  preview:
    runs-on: arm64-runner
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/preview
      with:
        dir: eks
        stack: ci

