name: CICD
on:
  push:
    branches:
    - main
    paths:
    - 'eks/**'

jobs:
  up:
    runs-on: arm64-runner
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/up
      with:
        dir: eks
        stack: ci