name: IAM Preview
on:
  pull_request:
    paths:
    - 'iam/**'

jobs:
  dev:
    runs-on: arm64-runner
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: unfor19/install-aws-cli-action@v1.0.3
      with:
        version: 2
        arch: arm64
    - uses: pulumi/setup-pulumi@v2
    - run: npm install && make reviewable
      working-directory: iam
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dev
        work-dir: iam
        comment-on-pr: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

